### Frontmatter tests ###
frontmatter_mandatory_fields:  ["title", "banner", "creation_date", "abstract", "template"]
frontmatter_mandatory_fields_by_templates:
  publication: ["conference_name"]

frontmatter_fields_value:
  category: ["web", "security", "video game"]

frontmatter_field_values_must_be_lowercase: ["category", "tags"]

# ensure that the posts that use a given template have a permanent_url that start with the right prefix
# Unspecified templates will be ignored
permanent_url_valid_prefixes_by_template: 
  blog_post: "/blog/"
  publication: "/publication/"
  talk: "/talk/"

files:
  valid_types: ["paper", "slides", "video"]
  valid_prefixes: ["/files"]
  valid_suffixes: ["-slides.pdf", "-paper.pdf"]

### Image tests ###
allowed_image_sources: ["mysite.com"] # list the domains from which images are included. use null or [] to forbidd external images.
min_image_width: 100 # minimal size for images in post. Use 0 to disable.
min_banner_width: 1900 # minimal size for the banner. Use 0 to disable.
banner_size_ratio: 1.8 # banner image ratio. Use 0 to disable. e.g 1.8 is for HD format 1900/1080