
##########################
# CollectionProcessor
# Plugins that process each collection after posts are parsed
##########################\###
CollectionProcessor:
  compute_full_collection_url:
    enable: true
  jsonld_collection:
    enable: true
  sort_collection:
    enable: true
    sort_by: update_date

##########################
# PostProcessor
# Plugins that process each post after they are parsed
##########################\###
PostProcessor:
  backup_media:
    backup_dir: backup/
    enable: false
  bibtex:
    enable: true
  compute_full_post_url:
    enable: true
  jsonld:
    enable: true
  read_time:
    enable: true
    wpm: 260

##########################
# SitePreparsing
# Site wide plugins that execute before the parsing start.
##########################\###
SitePreparsing:
  copy_dir:
    enable: true
    targets:
    - assets/js > generated/static/js
    - assets/css > generated/static/css
    - assets/images > generated/static/images
    - assets/svg > generated/static/svg
  frozen_images:
    enable: true
    input_dir: generated/static/images/
    output_dir: generated/static/images_frozen/
  image_info:
    enable: true
    input_dir: generated/static/images/
  image_resizer:
    enable: true
    input_dir: generated/static/images/
    max_width: 960
    quality: 90
  press:
    article_list: config/press.yaml
    enable: true
  responsive_images:
    additional_formats:
    - .webp
    cache_min_image_width: 400
    enable: true
    input_dir: generated/static/images/
    multithreading: false
    output_dir: generated/static/images_resized/
    template_file: config/generator_templates/responsive_images/img.html
    thumbnail_size:
    - 300
    - 600
    - 900
    - 1200
  thumbnails:
    enable: true
    input_dir: generated/static/images/
    output_dir: generated/static/thumbnails/
    thumbnail_sizes:
    - - 120
      - 120
    - - 96
      - 56

##########################
# SiteProcessor
# Plugins that process the whole site once after parsing.
##########################\###
SiteProcessor:
  related_posts:
    enable: true
    num_related_posts: 3

##########################
# SiteRendering
# Plugins that render additional pages after the rendering.
##########################\###
SiteRendering:
  autocomplete:
    enable: true
    excluded_terms:
    - post
    - top
    num_suggestions: 1000
    output_path: static/js/
  js_posts:
    enable: true
    meta_fields_to_output:
    - title
    - category
    - authors
    - permanent_url
    output_path: static/js/
    plugin_data_to_output:
    - responsive_banner
    - thumbnail_banner
  nlp:
    enable: true
    max_word_letters: 16
    min_word_letters: 3
    num_tfidf_keywords_per_post: 20
  rss:
    accent_color: 03A9F4
    analytics_code: UA-112090-10
    banner: /static/images/banner/fuller-house-exposing-high-end-poker-cheating-devices.jpg
    enable: true
    icon: /static/images/favicon/favicon-160x160.png
    layout_type: card
    logo_svg: /static/svg/
    num_posts: 10
    parser_config:
      code_display_line_num: true
      code_highlighting_theme: monokai
      template_dir: config/generator_templates/parser/rss/
    subtitle: Blog about web technologies and games with a focus performance and security.
    template: rss.xml
    title: Elie on Internet Security and Performance
    url: rss
  search:
    enable: true
    num_tfidf_keywords: 20
    output_path: static/js/
  sitemap:
    enable: true
    template: sitemap.xml

##########################
# TemplateFilter
# Plugins that define jinja2 filters to be used in templates
##########################\###
TemplateFilter:
  format_ts:
    enable: false
  str_to_list:
    enable: false
