press2:
  title: "mytitle 2"
  outlet: "outlet 2"
  author: "author 2"
  date: "mydate 2"
  url: "url 2"
  pdf: "link to pdf 2"

press1:
  title: "mytitle"
  outlet: "outlet"
  author: "author"
  date: "mydate"
  url: "url"
  pdf: "link to pdf"
